### ISSUE TITLE
Standalone words beginning in "beged cefet" appear as is, without dagesh kal inserted

### ISSUE THREAD

**Issue by ohizkiya** [metaist/hebphonics#33]
![image](https://user-images.githubusercontent.com/176449/103558360-89d3b480-4e82-11eb-996c-786fb5b072cc.png)

May be confusing for a beginning reader who may have learned that "vet" for instance cannot appear at the beginning of a word. (This assumes standalone words are being read, as per the current implementation.)

**Comment by metaist** [comment]
Hi @ohizkiya! Thanks for the pull requests and playing around with the tool.

To be clear, this tool is designed to help teachers search for words that match certain criteria, but because the source of the words is tanakh, weirdness abounds (e.g., `mapiq-alef`). 

The teachers who are currently using the tool (5 < n < 20) usually filter and sort by frequency (I still need to deploy your spelling correction :-) to avoid this kind of weirdness and eventually I'd like to add additional modern Hebrew texts so that they can pick words from there as well.

I'm not planning on fixing this because these are the actual words as they appear in tanakh, even though it's highly unusual in modern Hebrew.
